historicos = [
    "historico_CCO-1.pdf",
    "historico_CCO-2.pdf",
    "historico_CCO-3.pdf",
    "historico_CCO-4.pdf",
    "historico_CCO-5.pdf",
    "historico_SIN-1.pdf",
    "historico_SIN-2.pdf",
    "historico_SIN-3.pdf",
    "historico_SIN-4.pdf",
    "historico_SIN-5.pdf",
]

materias = {
    1: {
        "codigo": "XDES01",
        "nome": "Fundamentos da Programação",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": ["COM110","ECOP11A"],
        "situacao": 0,
        "parametro": 0,
    },
    2: {
        "codigo": "MAT00A",
        "nome": "Cálculo A",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": ["MAT001",],
        "situacao": 0,
        "parametro": 0,
    },
    3: {
        "codigo": "XMAC01",
        "nome": "Matemática Discreta",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": 0,
        "equivalentes": ["MAT015","MAT057","MAT017","ECOM01A"and "ECOM11A"],
        "situacao": 0,
        "parametro": 0,
    },
    4: {
        "codigo": "CAHC04",
        "nome": "Projeto Integrado",
        "ch": "32",
        "horario": [],
        "anual": 1,
        "requisito": 0,
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    5: {
        "codigo": "CTCO01",
        "nome": "Algoritmo e Estrutura de Dados 1",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["1"],
        "equivalentes": ["COM111","STCO01","ECOP02A"],
        "situacao": 0,
        "parametro": 0,
    },
    53: {
        "codigo": "CRSC03",
        "nome": "Arquitetura de Computadores 1",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": [],
        "equivalentes": ["CIC120","ELTD01A"and "ELTD11A"],
        "situacao": 0,
        "parametro": 0,
    },
    6: {
        "codigo": "CRSC04",
        "nome": "Arquitetura de Computadores 2",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["53"],
        "equivalentes": ["CIC121","ECOX01"],
        "situacao": 0,
        "parametro": 0,
    },
    7: {
        "codigo": "MAT00B",
        "nome": "Cálculo B",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["2"],
        "equivalentes": ["MAT002"],
        "situacao": 0,
        "parametro": 0,
    },
    8: {
        "codigo": "CMAC04",
        "nome": "Modelagem Computacional",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["2"],
        "equivalentes": ["CIC510"],
        "situacao": 0,
        "parametro": 0,
    },
    9: {
        "codigo": "CTCO02",
        "nome": "Algoritmo e Estrutura de Dados 2",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["5"],
        "equivalentes": ["COM112","STCO02"],
        "situacao": 0,
        "parametro": 0,
    },
    10: {
        "codigo": "XDES02",
        "nome": "Programação Orientada a Objetos",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["1"],
        "equivalentes": ["COM220","ECOP13A"],
        "situacao": 0,
        "parametro": 0,
    },
    11: {
        "codigo": "XDES04",
        "nome": "Engenharia de Software 1",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": ["C0M210","XDES04","ECOP13A"],
        "situacao": 0,
        "parametro": 0,
    },
    12: {
        "codigo": "CRSC02",
        "nome": "Sistemas Operacionais",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["5", "6"],
        "equivalentes": ["COM120","ECOS01A"and "ECOS11A"],
        "situacao": 0,
        "parametro": 0,
    },
    13: {
        "codigo": "CMAC03",
        "nome": "Algoritmos em Grafos",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["5"],
        "equivalentes": ["SIN110","SMAC03"],
        "situacao": 0,
        "parametro": 0,
    },
    14: {
        "codigo": "XMAC02",
        "nome": "Métodos Matemáticos para Análise de Dados",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["2", "3", "5"],
        "equivalentes": ["MAT013"],
        "situacao": 0,
        "parametro": 0,
    },
    15: {
        "codigo": "CTCO04",
        "nome": "Projeto e Análise de Algoritmos",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["9"],
        "equivalentes": ["CIC110"],
        "situacao": 0,
        "parametro": 0,
    },
    16: {
        "codigo": "XDES03",
        "nome": "Programação Web",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["10"],
        "equivalentes": ["COM222","ECOX05"],
        "situacao": 0,
        "parametro": 0,
    },
    17: {
        "codigo": "CDES05",
        "nome": "Programação Lógica e Funcional",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["3"],
        "equivalentes": ["CIC131"],
        "situacao": 0,
        "parametro": 0,
    },
    18: {
        "codigo": "XRSC01",
        "nome": "Redes de Computadores",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["12"or"41"],
        "equivalentes": ["COM240"],
        "situacao": 0,
        "parametro": 0,
    },
    19: {
        "codigo": "CRSC05",
        "nome": "Sistemas Embarcados",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["12"],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    20: {
        "codigo": "CMAC05",
        "nome": "Cálculo Numérico para Computação",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["7"],
        "equivalentes": ["CIC250"],
        "situacao": 0,
        "parametro": 0,
    },
    21: {
        "codigo": "CTCO03",
        "nome": "Análise e Projeto Orientados a Objeto",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["16"],
        "equivalentes": ["COM221"],
        "situacao": 0,
        "parametro": 0,
    },
    22: {
        "codigo": "CTCO05",
        "nome": "Teoria da Computação",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["15", "17"],
        "equivalentes": ["CIC132"],
        "situacao": 0,
        "parametro": 0,
    },
    23: {
        "codigo": "XPAD01",
        "nome": "Banco de Dados 1",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["9"or"36"],
        "equivalentes": ["COM230","ECOT03A" and "ECOT13A"],
        "situacao": 0,
        "parametro": 0,
    },
    24: {
        "codigo": "XMCO01",
        "nome": "Inteligência Artificial",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["14"or"39"],
        "equivalentes": ["CIC260","SIN260"],
        "situacao": 0,
        "parametro": 0,
    },
    25: {
        "codigo": "CMCO05",
        "nome": "Introdução a Computação Visual",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["14", "16"],
        "equivalentes": ["CIC271"],
        "situacao": 0,
        "parametro": 0,
    },
    26: {
        "codigo": "CTCO06",
        "nome": "Compiladores",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["22"],
        "equivalentes": ["CIC220"],
        "situacao": 0,
        "parametro": 0,
    },
    27: {
        "codigo": "XAHC02",
        "nome": "Interação Humano-Computador",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["16", "11"],
        "equivalentes": ["COM213"],
        "situacao": 0,
        "parametro": 0,
    },
    28: {
        "codigo": "XAHC03",
        "nome": "Metodologia Científica",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["TCC1"],
        "equivalentes": ["COM310"],
        "situacao": 0,
        "parametro": 0,
    },
    29: {
        "codigo": "XAHC01",
        "nome": "Computação e Sociedade",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": [],
        "equivalentes": ["COM312"],
        "situacao": 0,
        "parametro": 0,
    },
    30: {
        "codigo": "SAHC05",
        "nome": "Fundamentos de Sistemas de Informação",
        "ch": "32",
        "horario": [],
        "anual": 1,
        "requisito": 0,
        "equivalentes": ["SIN410"],
        "situacao": 0,
        "parametro": 0,
    },
    31: {
        "codigo": "IEPG01",
        "nome": "Empreendedorismo e Inovação",
        "ch": "48",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    32: {
        "codigo": "IEPG22",
        "nome": "Administração Aplicada",
        "ch": "32",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": ["SIN310"],
        "situacao": 0,
        "parametro": 0,
    },
    33: {
        "codigo": "STCO01",
        "nome": "Algoritmo e Programação 1",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["1"],
        "equivalentes": ["COM111","CTCO01","ECOP02A"],
        "situacao": 0,
        "parametro": 0,
    },
    34: {
        "codigo": "IEPG04",
        "nome": "Mapeamento de Processos",
        "ch": "32",
        "horario": [],
        "anual": 0,
        "requisito": 0,
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    35: {
        "codigo": "SDES05",
        "nome": "Engenharia de Software 2",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["11"],
        "equivalentes": ["COM211"],
        "situacao": 0,
        "parametro": 0,
    },
    36: {
        "codigo": "STCO02",
        "nome": "Algoritmo e Programação 2",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["33"],
        "equivalentes": ["COM112","CTCO02"],
        "situacao": 0,
        "parametro": 0,
    },
    37: {
        "codigo": "SRSC03",
        "nome": "Organização e Arquitetura de Computadores",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": [],
        "equivalentes": ["SIN120","CRSC04","ECOX01"],
        "situacao": 0,
        "parametro": 0,
    },
    38: {
        "codigo": "ECNO01",
        "nome": "Economia",
        "ch": "48",
        "horario": [],
        "anual": 0,
        "requisito": [],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    39: {
        "codigo": "XMAC02",
        "nome": "Métodos Matemáticos para Análise de Dados",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["2", "3", "33" or "9"],
        "equivalentes": ["MAT013"],
        "situacao": 0,
        "parametro": 0,
    },
    40: {
        "codigo": "SMAC03",
        "nome": "Grafos",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["33"],
        "equivalentes": ["SIN110"],
        "situacao": 0,
        "parametro": 0,
    },
    41: {
        "codigo": "SRSC02",
        "nome": "Sistemas Operacionais",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["33", "37"],
        "equivalentes": ["COM120","ECOS01A" and "ECOS11A"],
        "situacao": 0,
        "parametro": 0,
    },
    42: {
        "codigo": "IEPG14",
        "nome": "Comportamento Organizacional 1",
        "ch": "32",
        "horario": [],
        "anual": 0,
        "requisito": [],
        "equivalentes": ["SIN411"],
        "situacao": 0,
        "parametro": 0,
    },
    43: {
        "codigo": "SPAD02",
        "nome": "Banco de Dados 2",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["23"],
        "equivalentes": ["COM231"],
        "situacao": 0,
        "parametro": 0,
    },
    44: {
        "codigo": "SPAD03",
        "nome": "Introdução à Análise de Dados",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["23", "39"],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    45: {
        "codigo": "ADM515",
        "nome": "Gestão de Conhecimentos",
        "ch": "48",
        "horario": [],
        "anual": 0,
        "requisito": [],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    46: {
        "codigo": "SDES06",
        "nome": "Gerência de Projetos de Software",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["11"],
        "equivalentes": ["COM212"],
        "situacao": 0,
        "parametro": 0,
    },
    47: {
        "codigo": "IEPG10",
        "nome": "Engenharia Econômica",
        "ch": "48",
        "horario": [],
        "anual": 0,
        "requisito": [],
        "equivalentes": ["COM311"],
        "situacao": 0,
        "parametro": 0,
    },
    48: {
        "codigo": "SDES07",
        "nome": "Desenvolvimento de Sistemas Web",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["16", "11", "23"],
        "equivalentes": ["SIN412"],
        "situacao": 0,
        "parametro": 0,
    },
    49: {
        "codigo": "ADM03E",
        "nome": "Empreendedorismo Tecnológico",
        "ch": "48",
        "horario": [],
        "anual": 0,
        "requisito": ["31"],
        "equivalentes": ["SIN312"],
        "situacao": 0,
        "parametro": 0,
    },
    50: {
        "codigo": "XAHC03",
        "nome": "Gestão e Governança de TI",
        "ch": "64",
        "horario": [],
        "anual": 1,
        "requisito": ["32"],
        "equivalentes": ["SIN210"],
        "situacao": 0,
        "parametro": 0,
    },
    51: {
        "codigo": "TCC1",
        "nome": "TCC1",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["28"],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    52: {
        "codigo": "TCC2",
        "nome": "TCC2",
        "ch": "64",
        "horario": [],
        "anual": 0,
        "requisito": ["28"],
        "equivalentes": [],
        "situacao": 0,
        "parametro": 0,
    },
    
    
}
